sudo: required
dist: trusty
services:
  - docker

language: go

go:
  - 1.11.2

os:
  - linux
  - osx

env:
  matrix:
    - TARGETS="check"
    - TARGETS="testsuite"

  global:
    # Cross-compile for amd64 only to speed up testing.
    - GOX_FLAGS="-arch amd64"

addons:
  apt:
    update: true
    packages:
      - python-virtualenv
      - libpcap-dev
      - xsltproc
      - libxml2-utils
      - libsystemd-journal-dev
      - librpm-dev

before_install:
  - python --version
  - umask 022
  # Redo the travis setup but with the elastic/libbeat path. This is needed so the package path is correct
  - mkdir -p $HOME/gopath/src/github.com/maxverro/stockbeat/
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/maxverro/stockbeat/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/maxverro/stockbeat/
  - cd $HOME/gopath/src/github.com/maxverro/stockbeat/
  - if [ $TRAVIS_OS_NAME = osx ]; then pip install virtualenv; fi

# Skips installations step
install: 
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - make $TARGETS
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci


after_success:
  # Copy full.cov to coverage.txt because codecov.io requires this file
